CREATE DATABASE IF NOT EXISTS complexes_db;
\c complexes_db

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string,
  "years" int,
  "birthday" string,
  "weight" float,
  "height" int
);

CREATE TABLE "complex" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string
);

CREATE TABLE "schedule" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "start" time,
  "end" time
);

CREATE TABLE "schedule_complex" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "schedule_id" int,
  "complex_id" int,
  "available" boolean,
  "limit_people" int,
  "count_people" int
);

CREATE TABLE "user_complex" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "complex_id" int
);


ALTER TABLE "schedule_complex" ADD FOREIGN KEY ("schedule_id") REFERENCES "schedule" ("id");

ALTER TABLE "schedule_complex" ADD FOREIGN KEY ("complex_id") REFERENCES "complex" ("id");

ALTER TABLE "user_complex" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user_complex" ADD FOREIGN KEY ("complex_id") REFERENCES "complex" ("id");