version: '3.8'

services:
  sports-complexes-api:
    depends_on: 
      - volume_complexes
    build:
      context: .
    container_name: sports-complexes
    hostname: rest-server
    networks:
      - complexesnet
    ports:
      - 8081:8081
    environment:
      - PGUSER=${PGUSER:-admin}
      - PGPASSWORD=${PGPASSWORD?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE:-complexes_db}
    deploy:
      restart_policy:
        condition: on-failure
  roach:
    image: cockroachdb/cockroach:latest-v22.1
    container_name: roach
    hostname: db
    networks:
      - complexesnet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - volume_complexes:/cockroach/cockroach-data
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    command: start-single-node --insecure

volumes:
  volume_complexes:

networks:
  complexesnet:
    driver: bridge