// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Complex struct {
	ID     *int   `json:"id"`
	Name   string `json:"name"`
	Active *bool  `json:"active"`
}

type ComplexInput struct {
	ID     *int   `json:"id"`
	Name   string `json:"name"`
	Active *bool  `json:"active"`
}

type Schedule struct {
	ID    *int    `json:"id"`
	Start *string `json:"start"`
	End   *string `json:"end"`
}

type ScheduleComplex struct {
	ID          *int      `json:"id"`
	ScheduleID  int       `json:"schedule_id"`
	ComplexID   int       `json:"complex_id"`
	Available   *bool     `json:"available"`
	LimitPeople *int      `json:"limit_people"`
	CountPeople *int      `json:"count_people"`
	Schedule    *Schedule `json:"schedule"`
}

type ScheduleComplexInput struct {
	ID          *int  `json:"id"`
	ScheduleID  int   `json:"schedule_id"`
	ComplexID   int   `json:"complex_id"`
	Available   *bool `json:"available"`
	LimitPeople *int  `json:"limit_people"`
	CountPeople *int  `json:"count_people"`
}

type ScheduleInput struct {
	ID    *int    `json:"id"`
	Start *string `json:"start"`
	End   *string `json:"end"`
}

type User struct {
	ID       *int     `json:"id"`
	Name     string   `json:"name"`
	Years    int      `json:"years"`
	Birthday *string  `json:"birthday"`
	Weight   *float64 `json:"weight"`
	Height   *int     `json:"height"`
	Active   *bool    `json:"active"`
}

type UserComplex struct {
	ID        *int     `json:"id"`
	UserID    int      `json:"user_id"`
	ComplexID int      `json:"complex_id"`
	Active    *bool    `json:"active"`
	Users     *User    `json:"users"`
	Complexes *Complex `json:"complexes"`
}

type UserComplexInput struct {
	ID        *int  `json:"id"`
	UserID    int   `json:"user_id"`
	ComplexID int   `json:"complex_id"`
	Active    *bool `json:"active"`
}

type UserInput struct {
	ID       *int     `json:"id"`
	Name     string   `json:"name"`
	Years    *int     `json:"years"`
	Birthday *string  `json:"birthday"`
	Weight   *float64 `json:"weight"`
	Height   *int     `json:"height"`
	Active   *bool    `json:"active"`
}
